# Generated by Django 5.2.1 on 2025-06-03 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название номинации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинации',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='nomination.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='nomination.nomination', verbose_name='Номинация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_profiles', to='nomination.user', verbose_name='Пользователь-номинант')),
            ],
            options={
                'verbose_name': 'Номинант',
                'verbose_name_plural': 'Номинанты',
                'unique_together': {('nomination', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jury_profile', to='nomination.user', verbose_name='Пользователь - член жюри')),
            ],
            options={
                'verbose_name': 'Член жюри',
                'verbose_name_plural': 'Члены жюри',
            },
        ),
        migrations.CreateModel(
            name='JuryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='nomination.jury', verbose_name='Член жюри')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_evaluations', to='nomination.nominee', verbose_name='Номинант')),
            ],
            options={
                'verbose_name': 'Оценка жюри',
                'verbose_name_plural': 'Оценки жюри',
                'unique_together': {('jury', 'nominee')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата голосования')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nomination.nominee', verbose_name='Номинант')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nomination.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('user', 'nominee')},
            },
        ),
    ]
