# Generated by Django 5.2.1 on 2025-06-06 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Номинант', 'verbose_name_plural': 'Номинанты'},
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='is_active',
        ),
        migrations.AddField(
            model_name='nominee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('Y', 'За'), ('N', 'Против'), ('A', 'Воздержался')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения (необязательно)'),
        ),
    ]
