# Generated by Django 5.2.1 on 2025-06-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0002_alter_nominee_options_remove_nomination_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination.nomination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination.user')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('user', 'nomination')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', through='nomination.Subscription', through_fields=('user', 'nomination'), to='nomination.nomination'),
        ),
    ]
