# Generated by Django 5.2.1 on 2025-06-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0003_subscription_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
