# Generated by Django 5.2.1 on 2025-06-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0004_alter_nomination_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
