# Generated by Django 5.2.1 on 2025-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0005_alter_nomination_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='attachment',
            field=models.FileField(blank=True, help_text='Загрузите файл с описанием проекта', null=True, upload_to='nominee_files/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
