# Generated by Django 5.2.1 on 2025-06-17 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0006_nominee_attachment_alter_nomination_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
