# Generated by Django 4.2.23 on 2025-06-17 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomination', '0007_jury_photo_alter_nominee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-номинант'),
        ),
    ]
