# Generated by Django 4.2.23 on 2025-06-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0010_alter_nominee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_profiles', to='nomination.user', verbose_name='Пользователь-номинант'),
        ),
    ]
