# Generated by Django 4.2.23 on 2025-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0012_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
