# Generated by Django 4.2.23 on 2025-06-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0014_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
