# Generated by Django 4.2.23 on 2025-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0015_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NKexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания текущей записи')),
                ('exam_date', models.DateField(verbose_name='Дата проведения экзамена')),
                ('exam_task', models.ImageField(upload_to='exam_images/', verbose_name='Задание к экзамену')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(related_name='exams', to='nomination.user', verbose_name='Пользователи')),
            ],
        ),
    ]
