# Generated by Django 4.2.23 on 2025-06-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0016_nkexam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nkexam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
    ]
