# Generated by Django 4.2.23 on 2025-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0017_alter_nkexam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на проект'),
        ),
    ]
