# Generated by Django 4.2.23 on 2025-06-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0018_nomination_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='project_url',
        ),
        migrations.AddField(
            model_name='nominee',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на проект'),
        ),
    ]
