# Generated by Django 4.2.23 on 2025-06-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0020_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nkexam',
            name='users',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='NKexam',
        ),
    ]
