# Generated by Django 4.2.23 on 2025-06-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0024_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional username field', max_length=150, null=True, verbose_name='username'),
        ),
    ]
